### ISSUE TITLE
Roadmap 0.1.0

### ISSUE THREAD

**Issue by ptmt** [ptmt/react-native-desktop#1]
### General
- [ ] **Licenses:** #2 
- [ ] **Meta:** Improve Roadmap;
- [x] Make UIExplore alive;
- [x] Tests, CI;
- [ ] Accessability;
- [ ] **Clean up**;

### React.proj
- [x] RCTRedBox: fix crashes when reloading
- [ ] RCTRedBox: show SourceMap;
- [ ] RCTRedBox: show NSTableView stacktrace;
- [x] NSWindow should be able to restore size on start;
- [x] Loading screen (or at least loading hint);
- [x] Replace CADisplayLink (with NSTimer or CVDisplayLink?);
- [x] RCTUIManager: multiple `Exception thrown while executing UI block:`
- [x] Keyboard shortcuts (CMD+R for refresh, CMD+D for devmenu);
- [x] Flex;
- [x] Borders;
- [x] Predictable layout animation;
- [x] Autoresizing layout; (onLayout firing)
- [x] Problem with touch events (e.g. clicking on textbox and leaving). 
- [x] Mouse hover events;
- [ ] `<Text>` backgroundColor doesn't work

### RCTNetworking.proj
- [x] Resolve "Unable to load source map, RCTNetworking module is unavailable";

### RCTWebSocket.proj
- [x] Initial work

### RCTText
- [x] Display Hello World using `<Text/>`;
- [x] Custom fons, fonts weight, *RCT:Text" drawRect;
- [x] TextInput;
- [x] TextView;

**Comment by cgarvis** [comment]
Good job!  Keep it up.

**Comment by ptmt** [comment]
Finally get UIExplorer runnable. (These first examples works as is from React Native, no changes!)

![](http://i.imgur.com/QlhROpp.gif)

**Comment by yanivtal** [comment]
This is awesome. Thank you so much!

**Comment by ptmt** [comment]
New examples: 
![screenshot 2015-10-15 18 07 23](https://cloud.githubusercontent.com/assets/1004115/10513334/5f431c18-7360-11e5-82b9-a36a402a6bad.png)

Next: Continue to work on ScrollView, scroll events, text rendering. hitTest still broken sometimes.

**Comment by pvinis** [comment]
is there an easy way to try that out?

**Comment by ptmt** [comment]
@pvinis Short answer: no. I will add the bundled (ready-to-run) app when 0.1.0 will be ready.

**Comment by pvinis** [comment]
Cool. i mean also try it as in compile and run, so we can mess around with it

-- 
Pavlos Vinieratos


On 15 Oct 2015 at 16:50:25, Dmitry (notifications@github.com) wrote:

@pvinis Short answer: no. I will add the bundled (ready-to-run) app when 0.1.0 will be ready.

**Comment by ptmt** [comment]
@pvinis Basically you can run it the same way as React Native, though, I highly recommend waiting at least one week : )

**Comment by ptmt** [comment]
<img width="863" alt="screenshot 2015-10-17 15 31 23" src="https://cloud.githubusercontent.com/assets/1004115/10558069/1424bbb0-74dc-11e5-82c0-63b9371e7b97.png">

ScrollView naive&native arrived! 

Now it's time to do tests, TravicCI and other infrastructure tasks.

**Comment by ptmt** [comment]
http://i.imgur.com/ngju9d9.gifv. Scrolling has a weird reactions on wheel sometimes, but this is a still exciting milestone. Soon I will be able to start working on real app using `react-native-desktop` which should help to understand which features really important.

**Comment by ptmt** [comment]
Loading view and Dev menu arrived at some point. Need to add hotkeys, toggles though. 
<img width="271" alt="screenshot 2015-10-18 20 01 19" src="https://cloud.githubusercontent.com/assets/1004115/10564363/b971c6b4-75ca-11e5-9696-385c54f212bf.png">

**Comment by pvinis** [comment]
thats cool. i will try and see if i can make it run.

On Κυρ, Οκτ 18, 2015 at 16:04, ptmt/react-native-desktop
<reply@reply.github.com>
wrote:
Loading view and Dev menu arrived at some point. Need to add hotkeys, toggles
though.
screenshot 2015-10-18 20 01 19
[https://cloud.githubusercontent.com/assets/1004115/10564363/b971c6b4-75ca-11e5-9696-385c54f212bf.png]
[https://cloud.githubusercontent.com/assets/1004115/10564363/b971c6b4-75ca-11e5-9696-385c54f212bf.png]

—
Reply to this email directly or view it on GitHub
[https://github.com/ptmt/react-native-desktop/issues/1#issuecomment-149019268] .[https://github.com/notifications/beacon/AAGHiemR0vryJomgErR5x2QDgu2SFnQyks5o855VgaJpZM4GImzt.gif]

**Comment by ptmt** [comment]
Added TraviCCI (almost the exact one with react-native). Most of the tests passed after porting Cocoa Touch specific code to Cocoa code.
![image](https://cloud.githubusercontent.com/assets/1004115/10575142/118fb320-7674-11e5-9139-9d106c76a21d.png)

**Comment by ptmt** [comment]
Still need to fix a few bugs for a clean travis build.

**Comment by ptomasroos** [comment]
Sending some love, you're doing a great work!

**Comment by ptmt** [comment]
Ported some components, but there are now some other blocking major issues. Tests still failed randomly and only on CI. <img width="868" alt="screenshot 2015-10-20 19 19 30" src="https://cloud.githubusercontent.com/assets/1004115/10608147/311445b0-7757-11e5-9ef7-2e76107e4bb7.png">

**Comment by ptmt** [comment]
Borders: <img width="1471" alt="screenshot 2015-10-21 15 59 17" src="https://cloud.githubusercontent.com/assets/1004115/10633482/5c0b9a68-7804-11e5-9a85-fcfb9c843482.png">

I don't know how properly debug the TravisCI build. Tried with a clean install and build still worked, but not in the CI environment.

**Comment by freerunnering** [comment]
I love this, great work! :)

**Comment by ptmt** [comment]
Added `<Image />` initial support. I love it it's related to my ffirst pull request to react-native. <img width="986" alt="screenshot 2015-10-27 17 08 38" src="https://cloud.githubusercontent.com/assets/1004115/10756317/0ee807ec-7cc5-11e5-8fe4-6aaa8a9f7858.png">

**Comment by yanivtal** [comment]
Nice!

**Comment by jonnyyu** [comment]
great work!

**Comment by ptmt** [comment]
It's time to move on to next iteration
