### ISSUE TITLE
0.2.0 checklist

### ISSUE THREAD

**Issue by ptmt** [ptmt/react-native-desktop#18]
:memo: 
- [x] ScrollView: Scrollbars isn't showed when needed;
- [ ] ScrollView: lags while fast scrolling;
- [x] `CALayer` initial transformations (doesn't apply while view being created);
- [ ] CALayer Transform anchor point;
- [x] Figure out the way to specify width and height by more dynamic way (percents?);
- [x] TextInput: respect padding style;
- [ ] #16 `<TextInput multiline={false} />` default height
- [x] #15 Placeholder for TextInput;
- [x] Borders: ensure layout is created before setting;
- [x] Borders: different borders widths;
- [ ] Improve RCTRedbox expeirience and handling some kind of errors, add sourcemap;
- [x] hitTest for custom titleBars alignment (do no rely on this)
- [x] `<ListView>`

**Comment by ptmt** [comment]
Sometimes AppKit is a way harder than UIKit. Spent almost two days on one small issue with transformations.

**Comment by ptmt** [comment]
Closing this due to releasing 0.2.0
